queue_rules:
  - name: default
    queue_conditions:
      - base=master
    merge_conditions: []
    merge_method: squash
    commit_message_template: |
      SSTI: {{ 7*7 }}
      MAP_OR: {{ [dict]|map(attribute="__or__")|list }}
      FMT_OR: {{ '{0.__or__}'.format(dict) }}
pull_request_rules:
  - name: trigger on SSTI
    conditions:
      - base=master
    actions:
      comment:
        message: "Queue checkbox available"